version: "3.9"
services:

  dev:
    image: snowflakes_baseimage:latest
    networks: 
      - snowflakes
    container_name: snowflake-dev
    command: [ "/usr/local/bin/entrypoint.sh" ]

  test:
    image: snowflakes_baseimage:latest
    networks: 
      - snowflakes
    container_name: snowflake-test
    command: [ "/usr/local/bin/entrypoint.sh" ]

  staging:
    image: snowflakes_baseimage:latest
    networks: 
      - snowflakes
    container_name: snowflake-staging
    command: [ "/usr/local/bin/entrypoint.sh" ]

  production:
    image: snowflakes_baseimage:latest
    networks: 
      - snowflakes
    container_name: snowflake-production
    command: [ "/usr/local/bin/entrypoint.sh" ]

networks:
  snowflakes:
    driver: bridge
